# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  mod:
    cmds:
      - pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt
  train:
    cmds:
      - python data_train/train.py
  clean:
    cmds:
      - rm -rf output