log_url: https://tenhou.net/5/mjlog2json.cgi?
day_data_url: https://tenhou.net/sc/raw/dat/2023/scc20230101.html.gz
year_data_url: https://tenhou.net/sc/raw/scraw2022.zip

collect:
  whole_year_start: 2006
  whole_year_end: 2022
  day_start: "2023-01-01"
  day_end: "2023-02-01"

dest_path:
  raw: "tenhou_data/raw"
  catalog: "tenhou_data/catalog"
  log: "tenhou_data/log"
